name: Deploy Next.js to o2switch

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Setup pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm install

    - name: Build Next.js app
      run: pnpm run build

    - name: Deploy to o2switch via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: out/
        server-dir: /public_html/